version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - /var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock
      - db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build:
      context: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      - DEBUG=True
      - SECRET_KEY=u1=7b7g4)_fux6wi4mgg3r0ag9@sc_=
      - DATABASE_URL=psql://postgres:postgres@db:5432/postgres
      - ALLOWED_HOSTS=*
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db
  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend

volumes:
  db-volume: